amd-ucode
apple-fonts
archlinuxcn-keyring
base
base-devel
brightnessctl
btrfs-progs
catppuccin-gtk-theme-mocha
dae-avx2-bin
fastfetch
fcitx5-rime
fcitx5-theme-macos12
firefox-i18n-zh-cn
glfw
helix-git
jre-openjdk
kitty
linux-cachyos
linux-firmware-amdgpu
linux-firmware-mediatek
linux-firmware-realtek
lostfiles
man-db
networkmanager
niri
ntfs-3g
openssh
paru
rime-wanxiang-pinyin
rustup
tlp
tofi
ttf-apple-emoji
ttf-firacode-nerd
ttf-pingfang-git
visual-studio-code-bin
vulkan-radeon
waybar-minimal-git
wbg
wl-clipboard
xmcl-launcher
xwayland-satellite
yadm
zsh
zsh-autosuggestions
zsh-syntax-highlighting
