adobe-source-han-sans-cn-fonts
adobe-source-han-serif-cn-fonts
amd-ucode
archlinuxcn-keyring
auto-epp-rs
base
base-devel
brightnessctl
btrfs-progs
catppuccin-gtk-theme-mocha
dae-avx2-bin
fastfetch
fcitx5-rime
fcitx5-theme-macos12
flatpak
foot
google-chrome
helix-git
linux-cachyos
linux-firmware-amdgpu
linux-firmware-mediatek
linux-firmware-realtek
lostfiles
man-db
networkmanager
niri
noto-fonts-emoji
ntfs-3g
openssh
paru
pipewire-pulse
rime-wanxiang-pinyin
rustup
tofi
ttf-firacode-nerd
visual-studio-code-bin
vulkan-radeon
waybar-minimal-git
wl-clipboard
xwayland-satellite
yadm
zsh
zsh-autosuggestions
zsh-syntax-highlighting
