listener {
  timeout = 100
  on-timeout = brightnessctl -s set 1
  on-resume = brightnessctl -r
}

listener {
  timeout = 100
  on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
  on-resume = brightnessctl -rd rgb:kbd_backlight
}
