amd-ucode
apple-fonts
archlinuxcn-keyring
auto-epp-rs
base
base-devel
bibata-cursor-git
brightnessctl
btrfs-progs
catppuccin-gtk-theme-mocha
dae-avx2-bin
fastfetch
fcitx5-rime
fcitx5-theme-macos12
firefox-developer-edition-i18n-zh-cn
greetd
helix-git
hyprland
hyprpaper
keyd
kitty
less
linux-firmware-amdgpu
linux-firmware-mediatek
linux-firmware-realtek
linux-zen
man-db
mpv
networkmanager
openssh
paru
rime-wanxiang-pinyin
rustup
ttf-apple-emoji
ttf-firacode-nerd
ttf-pingfang-git
vi
vulkan-radeon
waybar
wl-clipboard
wofi
xdg-desktop-portal-gtk
xdg-desktop-portal-hyprland
yadm
zsh
zsh-autosuggestions
zsh-syntax-highlighting
