amd-ucode
archlinuxcn-keyring
auto-epp-rs
base
base-devel
bibata-cursor-git
brightnessctl
catppuccin-gtk-theme-mocha
dae-avx2-bin
fastfetch
fcitx5-rime
fcitx5-theme-macos12
firefox-developer-edition-i18n-zh-cn
git
greetd
helix-git
hyprland
hyprpaper
kitty
less
linux-firmware
linux-zen
man-db
mpv
networkmanager
openssh
otf-apple-pingfang
paru
rime-wanxiang-pinyin
rustup
ttf-apple-emoji
ttf-firacode-nerd
unzip
vi
vulkan-radeon
waybar
wl-clipboard
wofi
xdg-desktop-portal-gtk
xdg-desktop-portal-hyprland
yadm
zsh
zsh-autosuggestions
zsh-syntax-highlighting
