adobe-source-han-sans-cn-fonts
amd-ucode
archlinuxcn-keyring
auto-epp-rs
base
base-devel
bibata-cursor-git
brightnessctl
catppuccin-fcitx5-git
dae-git
fastfetch
fcitx5-rime
firefox-developer-edition-i18n-zh-cn
git
greetd
helix-git
hyprland
hyprpaper
kitty
less
linux-firmware
linux-zen
man-db
mpv-git
networkmanager
noto-fonts-emoji
openssh
paru
rime-frost-git
rustup
tree
ttf-firacode-nerd
vi
vulkan-radeon
waybar
wl-clipboard-rs
wofi
xdg-desktop-portal-gtk
xdg-desktop-portal-hyprland
yadm-git
zed
zsh
zsh-autosuggestions-git
zsh-syntax-highlighting-git
